
num_colors: 8
grid_size: 8
trajectory_length: 100
num_walls: 4

train_tasks: [
    [0, 1, 4, 5, 0, 1],
    [0, 1, 4, 5, 2, 3],
    [0, 1, 6, 7, 2, 3],
    [2, 3, 0, 1, 4, 5],
    [2, 3, 6, 7, 2, 3],
    [2, 3, 6, 7, 4, 5],
    [4, 5, 0, 1, 4, 5],
    [4, 5, 0, 1, 6, 7],
    [4, 5, 2, 3, 6, 7],
    [6, 7, 2, 3, 0, 1],
    [6, 7, 2, 3, 6, 7],
    [6, 7, 4, 5, 0, 1],
    [0, 1, 6, 7, 4, 5],
    [2, 3, 0, 1, 6, 7],
    [4, 5, 2, 3, 0, 1],
    [6, 7, 4, 5, 2, 3],
]

test_tasks: [
  [0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3]
]